package net;
/**
 * Interface applied to all instrumented classes.
 * Implementation is automatically generated by java agent at load time
 */
public interface Tagged {
	public Object getMetadataTag();
	public void setMetadataTag(Object tag);
}
